apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: anuddeeph/apache-webserver-php
        volumeMounts:
        - name: my-volume1
          mountPath: /data1
      volumes:
      - name: my-volume1
        persistentVolumeClaim:
          claimName: pvc1
